// react/src/components/LogicPuzzleFrame.jsx

import React, { useEffect, useRef, useMemo } from 'react';
import LPCellPoints from '../models/LPCellPoints';

// Default constants
const MARGIN_X = 10;
const MARGIN_Y = 10;
const HINT_SIZE = 20;

const LogicPuzzleFrame = ({
    canvasWidth = 300,
    canvasHeight = 300,
    verticalCount = 5,
    horizontalCount = 5,
    lPCells = null,
    lPHints = null,
    cellIsShow = true,
    onClickCell
}) => {
    const canvasRef = useRef(null);

    // Computed equivalents using useMemo
    const lPCellPoints = useMemo(() => {
        // We need to calculate cellSize first inside useMemo because it depends on canvas size
        // But wait, cellSize is also used for styles etc.
        // Let's re-calculate it here.

        // hintWidth/Height
        const leftHintMaxCount = Math.floor(horizontalCount / 2 + (horizontalCount % 2));
        const topHintMaxCount = Math.floor(verticalCount / 2 + (verticalCount % 2));
        const hintWidth = leftHintMaxCount * HINT_SIZE;
        const hintHeight = topHintMaxCount * HINT_SIZE;

        // cellSize
        const w = Math.floor(
            (canvasWidth - MARGIN_X * 2 - hintWidth) / horizontalCount
        );
        const h = Math.floor(
            (canvasHeight - MARGIN_Y * 2 - hintHeight) / verticalCount
        );
        const cellSize = Math.min(w, h);

        return new LPCellPoints({
            marginX: MARGIN_X,
            marginY: MARGIN_Y,
            horizontalCount,
            verticalCount,
            cellSize,
            hintSize: HINT_SIZE
        });
    }, [horizontalCount, verticalCount, canvasWidth, canvasHeight]);

    // Derived values for rendering
    const topHintMaxCount = Math.floor(verticalCount / 2 + (verticalCount % 2));
    const leftHintMaxCount = Math.floor(horizontalCount / 2 + (horizontalCount % 2));
    const hintWidth = leftHintMaxCount * HINT_SIZE;
    const hintHeight = topHintMaxCount * HINT_SIZE;
    const leftSpaceWidth = MARGIN_X + hintWidth;
    const topSpaceHeight = MARGIN_Y + hintHeight;
    const cellSize = lPCellPoints.cellSize; // Get from the created object
    const cellsWidth = cellSize * horizontalCount;
    const cellsHeight = cellSize * verticalCount;


    // Drawing functions
    const render = () => {
        const canvas = canvasRef.current;
        if (!canvas) return;
        const context = canvas.getContext('2d');
        if (!context) return;

        // Helper functions for drawing
        const clearRect = (x, y, w, h) => context.clearRect(x, y, w, h);
        const fillRect = (x, y, w, h, options = {}) => {
            context.fillStyle = options.fillStyle || "#000000";
            context.fillRect(x, y, w, h);
        };
        const fillText = (text, x, y, size, options = {}) => {
            context.fillStyle = options.fillStyle || "#000000";
            context.fillText(text, x, y, size);
        };
        const strokeLine = (x1, y1, x2, y2, options = {}) => {
            context.lineWidth = options.lineWidth !== undefined ? options.lineWidth : 1;
            context.strokeStyle = options.strokeStyle || "#000000";
            context.setLineDash(options.lineDash || []);
            context.beginPath();
            context.moveTo(x1, y1);
            context.lineTo(x2, y2);
            context.stroke();
        };
        const strokeNoPaint = (x, y, w, h, options) => {
            strokeLine(x, y, x + w, y + h, options);
            strokeLine(x + w, y, x, y + h, options);
        };

        // Render Logic
        // resetCanvas
        clearRect(0, 0, canvas.width, canvas.height);
        fillRect(0, 0, canvas.width, canvas.height, { fillStyle: "#ffffff" });

        // renderHints
        if (lPHints) {
            context.textAlign = "center";
            // Vertical hints (top)
            lPHints.vertical.forEach((line, i) => {
                const reversed = line.slice().reverse();
                reversed.forEach((hint, j) => {
                    fillText(
                        String(hint),
                        leftSpaceWidth + cellSize * i + cellSize / 2,
                        topSpaceHeight - (HINT_SIZE * j + 8),
                        HINT_SIZE
                    );
                });
            });
            // Horizontal hints (left)
            lPHints.horizontal.forEach((line, i) => {
                const reversed = line.slice().reverse();
                reversed.forEach((hint, j) => {
                    fillText(
                        String(hint),
                        leftSpaceWidth - (HINT_SIZE * j + 8),
                        topSpaceHeight + cellSize * i + cellSize / 2,
                        HINT_SIZE
                    );
                });
            });
        }

        // renderCells
        if (lPCells && cellIsShow) {
            lPCells.cellIds.forEach(cellId => {
                const cell = lPCells.getCell(cellId);
                const point = lPCellPoints.getPoint(cell.id);
                if (!point) return;

                fillRect(point.x, point.y, point.w, point.h, { fillStyle: "#ffffff" });
                switch (cell.s) {
                    case 1:
                        fillRect(point.x, point.y, point.w, point.h, { fillStyle: cell.c });
                        break;
                    case 2:
                        strokeNoPaint(point.x, point.y, point.w, point.h, { strokeStyle: cell.c });
                        break;
                    default:
                        break;
                }
            });
        }

        // renderFrame
        for (let i = 0; i < verticalCount + 1; i++) {
            const isFirstLine = i === 0;
            const isLastLine = i === verticalCount;
            const isSeparationLine = !isFirstLine && !isLastLine && i % 5 === 0;
            const lineWidth = isSeparationLine ? 2 : 1;
            const lineDash = isFirstLine || isLastLine || isSeparationLine ? [] : [1, 1];
            strokeLine(
                leftSpaceWidth,
                topSpaceHeight + cellSize * i,
                leftSpaceWidth + cellsWidth,
                topSpaceHeight + cellSize * i,
                { lineWidth, lineDash }
            );
        }
        for (let i = 0; i < horizontalCount + 1; i++) {
            const isFirstLine = i === 0;
            const isLastLine = i === horizontalCount;
            const isSeparationLine = !isFirstLine && !isLastLine && i % 5 === 0;
            const lineWidth = isSeparationLine ? 2 : 1;
            const lineDash = isFirstLine || isLastLine || isSeparationLine ? [] : [1, 1];
            strokeLine(
                leftSpaceWidth + cellSize * i,
                topSpaceHeight,
                leftSpaceWidth + cellSize * i,
                topSpaceHeight + cellsHeight,
                { lineWidth, lineDash }
            );
        }
    };

    // Re-render when props change
    useEffect(() => {
        render();
    }, [
        lPCells,
        lPHints,
        cellIsShow,
        canvasWidth,
        canvasHeight,
        verticalCount,
        horizontalCount,
        lPCellPoints // implicitly includes dependencies
    ]);

    const onClickCanvas = (event) => {
        const canvas = canvasRef.current;
        if (!canvas) return;

        // Get mouse position relative to canvas
        const rect = canvas.getBoundingClientRect();
        const offsetX = event.clientX - rect.left;
        const offsetY = event.clientY - rect.top;

        lPCellPoints.cellIds.forEach(cellId => {
            const point = lPCellPoints.getPoint(cellId);
            if (
                point.x <= offsetX &&
                offsetX <= point.x + point.w &&
                point.y <= offsetY &&
                offsetY <= point.y + point.h
            ) {
                if (onClickCell) {
                    onClickCell(cellId);
                }
            }
        });
    };

    return (
        <canvas
            width={canvasWidth}
            height={canvasHeight}
            onClick={onClickCanvas}
            ref={canvasRef}
            style={{ border: '1px solid #ccc' }} // Optional: add border to see canvas
        />
    );
};

export default LogicPuzzleFrame;

// src/components/LogicPuzzleFrame.vue
<template>
  <canvas
    :width="canvasWidth"
    :height="canvasHeight"
    @click="onClickCanvas"
    ref="Canvas"
  ></canvas>
</template>

<script>
// TODO: セルの色
// TODO: 5セルごとに太線
import LPCellPoints from "../models/LPCellPoints";

export default {
  name: "LogicPuzzleFrame",
  props: {
    canvasWidth: {
      type: Number,
      default: 300
    },
    canvasHeight: {
      type: Number,
      default: 300
    },
    /**
     * 縦セル数
     */
    verticalCount: {
      type: Number,
      default: 5
    },
    /**
     * 横セル数
     */
    horizontalCount: {
      type: Number,
      default: 5
    },
    lPCells: {
      type: Object,
      default: null
    },
    lPHints: {
      type: Object,
      default: null
    },
    cellIsShow: {
      type: Boolean,
      default: true
    }
  },
  data() {
    return {
      canvas: null,
      marginX: 10,
      marginY: 10,
      hintSize: 20
    };
  },
  mounted() {
    this.canvas = this.$refs.Canvas;
    this.render();
  },
  watch: {
    lPCells() {
      this.render();
    },
    lPHints() {
      this.render();
    },
    cellIsShow() {
      this.render();
    }
  },
  computed: {
    context() {
      if (!this.canvas || !this.canvas.getContext) {
        return null;
      }
      return this.canvas.getContext("2d");
    },
    lPCellPoints() {
      return new LPCellPoints({
        marginX: this.marginX,
        marginY: this.marginY,
        horizontalCount: this.horizontalCount,
        verticalCount: this.verticalCount,
        cellSize: this.cellSize,
        hintSize: this.hintSize
      });
    },
    topHintMaxCount() {
      return Math.floor(this.verticalCount / 2 + (this.verticalCount % 2));
    },
    leftHintMaxCount() {
      return Math.floor(this.horizontalCount / 2 + (this.horizontalCount % 2));
    },
    hintWidth() {
      return this.leftHintMaxCount * this.hintSize;
    },
    hintHeight() {
      return this.topHintMaxCount * this.hintSize;
    },
    leftSpaceWidth() {
      return this.marginX + this.hintWidth;
    },
    topSpaceHeight() {
      return this.marginY + this.hintHeight;
    },
    cellsWidth() {
      return this.cellSize * this.horizontalCount;
    },
    cellsHeight() {
      return this.cellSize * this.verticalCount;
    },
    cellSize() {
      const w = Math.floor(
        (this.canvas.width - this.marginX * 2 - this.hintWidth) /
          this.horizontalCount
      );
      const h = Math.floor(
        (this.canvas.height - this.marginY * 2 - this.hintHeight) /
          this.verticalCount
      );
      return Math.min(w, h);
    }
  },
  methods: {
    onClickCanvas(event) {
      this.lPCellPoints.cellIds.forEach(cellId => {
        const point = this.lPCellPoints.getPoint(cellId);
        if (this.isChecked(event.offsetX, event.offsetY, point)) {
          this.onClickCell(cellId);
        }
      });
    },
    onClickCell(cellId) {
      this.$emit("click-cell", cellId);
    },
    isChecked(offsetX, offsetY, point) {
      return (
        point.x <= offsetX &&
        offsetX <= point.x + point.w &&
        point.y <= offsetY &&
        offsetY <= point.y + point.h
      );
    },
    render() {
      this.resetCanvas();
      this.renderHints();
      this.renderCells();
      this.renderFrame();
    },
    resetCanvas() {
      this.clearRect(0, 0, this.canvas.width, this.canvas.height);
      this.fillRect(0, 0, this.canvas.width, this.canvas.height, {
        fillStyle: "#ffffff"
      });
    },
    renderFrame() {
      for (let i = 0; i < this.verticalCount + 1; i++) {
        const isFirstLine = i === 0;
        const isLastLine = i === this.verticalCount;
        const isSeparationLine = !isFirstLine && !isLastLine && i % 5 === 0;
        const lineWidth = isSeparationLine ? 2 : 1;
        const lineDash =
          isFirstLine || isLastLine || isSeparationLine ? [] : [1, 1];
        this.strokeLine(
          this.leftSpaceWidth,
          this.topSpaceHeight + this.cellSize * i,
          this.leftSpaceWidth + this.cellsWidth,
          this.topSpaceHeight + this.cellSize * i,
          { lineWidth, lineDash }
        );
      }
      for (let i = 0; i < this.horizontalCount + 1; i++) {
        const isFirstLine = i === 0;
        const isLastLine = i === this.horizontalCount;
        const isSeparationLine = !isFirstLine && !isLastLine && i % 5 === 0;
        const lineWidth = isSeparationLine ? 2 : 1;
        const lineDash =
          isFirstLine || isLastLine || isSeparationLine ? [] : [1, 1];
        this.strokeLine(
          this.leftSpaceWidth + this.cellSize * i,
          this.topSpaceHeight,
          this.leftSpaceWidth + this.cellSize * i,
          this.topSpaceHeight + this.cellsHeight,
          { lineWidth, lineDash }
        );
      }
    },
    renderHints() {
      if (!this.lPHints) {
        return;
      }

      this.context.textAlign = "center";

      // 上側ヒントの表示
      this.lPHints.vertical.forEach((line, i) => {
        const reversed = line.slice().reverse();
        reversed.forEach((hint, j) => {
          this.fillText(
            String(hint),
            this.leftSpaceWidth + this.cellSize * i + this.cellSize / 2,
            this.topSpaceHeight - (this.hintSize * j + 8),
            this.hintSize
          );
        });
      });

      // 左側ヒントの表示
      this.lPHints.horizontal.forEach((line, i) => {
        const reversed = line.slice().reverse();
        reversed.forEach((hint, j) => {
          this.fillText(
            String(hint),
            this.leftSpaceWidth - (this.hintSize * j + 8),
            this.topSpaceHeight + this.cellSize * i + this.cellSize / 2,
            this.hintSize
          );
        });
      });
    },
    renderCells() {
      if (!this.lPCells || !this.cellIsShow) {
        return;
      }

      this.lPCells.cellIds.forEach(cellId => {
        const cell = this.lPCells.getCell(cellId);
        this.renderCell(cell);
      });
    },
    renderCell(cell) {
      const point = this.lPCellPoints.getPoint(cell.id);
      if (!point) return;

      this.fillRect(point.x, point.y, point.w, point.h, {
        fillStyle: "#ffffff"
      });
      switch (cell.s) {
        case 1:
          this.fillRect(point.x, point.y, point.w, point.h, {
            fillStyle: cell.c
          });
          break;
        case 2:
          this.strokeNoPaint(point.x, point.y, point.w, point.h, {
            strokeStyle: cell.c,
          });
          break;
        default:
          // NOP
          break;
      }
    },
    clearRect(x, y, w, h) {
      this.context.clearRect(x, y, w, h);
    },
    fillText(text, x, y, size, options) {
      const _options = {
        fillStyle: "#000000",
        ...options
      };
      this.context.fillStyle = _options.fillStyle;
      this.context.fillText(text, x, y, size);
    },
    fillRect(x, y, w, h, options) {
      const _options = {
        fillStyle: "#000000",
        ...options
      };
      this.context.fillStyle = _options.fillStyle;
      this.context.fillRect(x, y, w, h);
    },
    strokeLine(x1, y1, x2, y2, options) {
      const _options = {
        lineWidth: 1,
        lineDash: [],
        strokeStyle: "#000000",
        ...options
      };
      this.context.lineWidth = _options.lineWidth;
      this.context.strokeStyle = _options.strokeStyle;
      this.context.setLineDash(_options.lineDash);
      this.context.beginPath();
      this.context.moveTo(x1, y1);
      this.context.lineTo(x2, y2);
      this.context.stroke();
    },
    strokeNoPaint(x, y, w, h, options) {
      this.strokeLine(x, y, x + w, y + h, options);
      this.strokeLine(x + w, y, x, y + h, options);
    }
  }
};
</script>

<style scoped></style>
