// react/src/components/LogicPuzzleGenerator.jsx

import React, { useState, useEffect, useCallback } from 'react';
import LogicPuzzleFrame from './LogicPuzzleFrame';
import LPHints from '../models/LPHints';
import LPCells from '../models/LPCells';

const LogicPuzzleGenerator = () => {
    const [verticalCount, setVerticalCount] = useState(5);
    const [horizontalCount, setHorizontalCount] = useState(5);
    const [canvasWidth] = useState(500);
    const [canvasHeight] = useState(500);
    const [lPHints, setLPHints] = useState(null);
    const [lPCells, setLPCells] = useState(null);
    const [cellIsShow, setCellIsShow] = useState(true);

    // Initial setup and when counts change
    useEffect(() => {
        const newCells = LPCells.empty(verticalCount, horizontalCount);
        setLPCells(newCells);
        setLPHints(LPHints.createByLPCells(newCells));
    }, [verticalCount, horizontalCount]);

    // Update hints when cells change
    useEffect(() => {
        if (lPCells) {
            setLPHints(LPHints.createByLPCells(lPCells));
        }
    }, [lPCells]);

    const onClickCell = useCallback((cellId) => {
        setLPCells(prev => prev.updateNextState(cellId));
    }, []);

    const onClickShowButton = () => {
        setCellIsShow(prev => !prev);
    };

    // Handlers for inputs to ensure number type
    const onChangeVertical = (e) => setVerticalCount(Number(e.target.value));
    const onChangeHorizontal = (e) => setHorizontalCount(Number(e.target.value));

    return (
        <div>
            <p>
                <label>
                    縦:
                    <input type="number" value={verticalCount} onChange={onChangeVertical} />
                </label>
            </p>
            <p>
                <label>
                    横:
                    <input type="number" value={horizontalCount} onChange={onChangeHorizontal} />
                </label>
            </p>
            <p>
                <button onClick={onClickShowButton}>
                    {cellIsShow ? 'セル非表示' : 'セル表示'}
                </button>
            </p>
            <LogicPuzzleFrame
                canvasWidth={canvasWidth}
                canvasHeight={canvasHeight}
                verticalCount={verticalCount}
                horizontalCount={horizontalCount}
                lPHints={lPHints}
                lPCells={lPCells}
                cellIsShow={cellIsShow}
                onClickCell={onClickCell}
            />
            <dl>
                <dt>Hints:</dt>
                <dd>
                    <textarea
                        value={lPHints ? lPHints.json : ''}
                        rows="5"
                        cols="50"
                        readOnly
                    />
                </dd>
                <dt>Cells:</dt>
                <dd>
                    <textarea
                        value={lPCells ? lPCells.json : ''}
                        rows="5"
                        cols="50"
                        readOnly
                    />
                </dd>
            </dl>
        </div>
    );
};

export default LogicPuzzleGenerator;

// src/components/LogicPuzzleGenerator.vue
<template>
  <div>
    <p>
      <label
        >縦:
        <input type="number" v-model.number="verticalCount" />
      </label>
    </p>
    <p>
      <label
        >横:
        <input type="number" v-model.number="horizontalCount" />
      </label>
    </p>
    <p>
      <button @click="onClickShowButton">{{ cellIsShow ? 'セル非表示' : 'セル表示' }}</button>
    </p>
    <LogicPuzzleFrame
      :canvas-width="canvasWidth"
      :canvas-height="canvasHeight"
      :vertical-count="verticalCount"
      :horizontal-count="horizontalCount"
      :l-p-hints="lPHints"
      :l-p-cells="lPCells"
      :cell-is-show="cellIsShow"
      @click-cell="onClickCell"
    />
    <dl>
      <dt>
        Hints:
      </dt>
      <dd>
        <textarea v-if="lPHints" v-model="lPHints.json" rows="5" cols="50" readonly />
      </dd>
      <dt>
        Cells:
      </dt>
      <dd>
        <textarea v-if="lPCells" v-model="lPCells.json" rows="5" cols="50"  readonly />
      </dd>
    </dl>
  </div>
</template>

<script>
import LogicPuzzleFrame from "./LogicPuzzleFrame";
import LPHints from "../models/LPHints";
import LPCells from "../models/LPCells";

export default {
  name: "LogicPuzzleGenerator",
  components: {
    LogicPuzzleFrame
  },
  data() {
    return {
      verticalCount: 5,
      horizontalCount: 5,
      canvasWidth: 500,
      canvasHeight: 500,
      margin: {
        x: 10,
        y: 10
      },
      hintSize: 20,
      lPHints: null,
      lPCells: null,
      cellIsShow: true,
    };
  },
  mounted() {
    this.lPCells = LPCells.empty(this.verticalCount, this.horizontalCount);
    this.lPHints = LPHints.createByLPCells(this.lPCells);
  },
  computed: {},
  watch: {
    verticalCount() {
      this.onChangeSize();
      this.lPCells = LPCells.empty(this.verticalCount, this.horizontalCount);
      this.lPHints = LPHints.createByLPCells(this.lPCells);
    },
    horizontalCount() {
      this.onChangeSize();
      this.lPCells = LPCells.empty(this.verticalCount, this.horizontalCount);
      this.lPHints = LPHints.createByLPCells(this.lPCells);
    },
    lPCells() {
      this.lPHints = LPHints.createByLPCells(this.lPCells);
    }
  },
  methods: {
    onChangeSize() {},
    onClickCell(cellId) {
      this.lPCells = this.lPCells.updateNextState(cellId);
    },
    onClickShowButton() {
      this.cellIsShow = !this.cellIsShow;
    },
  }
};
</script>
